spring:
  application:
    name: api-service

  datasource:
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://35.229.239.168:3306/buddyto_sep_qa
    password: Letsbounce123


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

server:
  port: 8081

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0




zuul:
  prefix: /api
  routes:
    candidate-service:
      path: /candidate-service/**
      url: http://localhost:8086

candidate-api-url-rhid: http://localhost:8081/api/candidate-service/candidate-end-point/by-rhid
